version: '3.1'

services:

  app:
    build: .
    restart: always
    ports:
      - '8080:8080'
    depends_on:
      - postgres

  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: weather_app
    volumes:
      - ./src/main/resources/db-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
